pyconjp/pyconjpbot

- pyconjpbot/plugins/reaction.py
> [add] sakusaku panda reaction.

- ChangeLog.txt
- README.md
- pyconjpbot/plugins/pycamp.py
- pyconjpbot/plugins/term.py
* https://pyconjp.atlassian.net/browse/ISSHA-497
> ISSHA-497 add pycamp command

- ChangeLog.txt
- pyconjpbot/plugins/translator.py
* Microsoft Translator API使うためのトークンは一定期間で期限切れするらしい
* トークンを延長する、または取り直すようにする
> ISSHA-745 トークンの期限切れに対応

- ChangeLog.txt
- pyconjpbot/plugins/pycamp.py
* pycampのチケット作成のテンプレートをソース埋め込みからスプレッドシートに変更する
* https://docs.google.com/spreadsheets/d/1LEtpNewhAFSf_vtkhTsWi6JGs2p-7XHZE8yOshagz0I/edit#gid=0
> ISSHA-769 pycampコマンドのテンプレートをスプレッドシートに変更

- ChangeLog.txt
- pyconjpbot/plugins/jira.py
* https://pyconjp.atlassian.net/browse/ISSHA-849
* 複数のJIRA issue idに対応
> ISSHA-849 add multiple JIRA issue id support

- ChangeLog.txt
- pyconjpbot/plugins/pycamp.py
* bot: pycampコマンドでイベントの状況を取得
* https://pyconjp.atlassian.net/browse/ISSHA-909
* $pycamp summary コマンドで、今後開催予定の camp の情報を応答するコマンド
> ISSHA-909 pycamp summary コマンド

- ChangeLog.txt
- README.md
- pyconjpbot/plugins/pycamp.py
https://pyconjp.atlassian.net/browse/ISSHA-912
> ISSHA-912 add -party option to pycamp summary command

- ChangeLog.txt
- pyconjpbot/plugins/pycamp.py
* https://pyconjp.atlassian.net/browse/ISSHA-944
> ISSHA-944 fix target_date bug for pycamp create

- ChangeLog.txt
- README.md
- pyconjpbot/plugins/lgtm.py
- pyconjpbot/plugins/term.py
- requirements.txt
* https://pyconjp.atlassian.net/browse/ISSHA-947
> ISSHA-947 lgtm command

- pyconjpbot/plugins/jira.py
- slackbot_settings.py.sample
* https://pyconjp.atlassian.net/browse/INU-45
> Fix a jira plugin templete for INU project

- ChangeLog.txt
- pyconjpbot/plugins/pycamp.py
* https://pyconjp.atlassian.net/browse/ISSHA-1286
> ISSHA-1286 check pycamp event title

- ChangeLog.txt
- README.md
- pyconjpbot/plugins/pycamp.py
* https://pyconjp.atlassian.net/browse/ISSHA-1416
* pycampのスタッフ、TAで2回参加した人を数えて出力するコマンド
> Issha 1416 pycamp staff count

- ChangeLog.txt
- requirements.txt
* https://pyconjp.atlassian.net/browse/ISSHA-1454
> ISSHA-1454 fix JIRA error

- ChangeLog.txt
- README.md
- pyconjpbot/plugins/lgtm.py
* https://pyconjp.atlassian.net/browse/ISSHA-967
> ISSHA-967 lgtmコマンドで画像を3つ生成

- ChangeLog.txt
- pyconjpbot/plugins/pycamp.py
- slackbot_settings.py.sample
* https://pyconjp.atlassian.net/browse/ISSHA-1700
> ISSHA-1700 pycamp createコマンドが動作しない問題に対応

- pyconjpbot/google_plugins/gadmin.py
* https://pyconjp.atlassian.net/browse/ISSHA-2223
- message.sentは存在せず落ちるようになっていたので他の部分で使っているbotsendを使った
- エラー文言送ったあとに後続の処理が実行されていたのでAdminチェックしている意味がなく、とりあえずreturnしておいた
> adminチェックの修正

- .github/workflows/linter.yml
- pyconjpbot/botmessage.py
- pyconjpbot/google_plugins/folder_model.py
- pyconjpbot/google_plugins/gadmin.py
- pyconjpbot/google_plugins/google.py
- pyconjpbot/google_plugins/google_api.py
- pyconjpbot/google_plugins/googledrive.py
- pyconjpbot/plugins/calc.py
- pyconjpbot/plugins/github.py
- pyconjpbot/plugins/greeting.py
- pyconjpbot/plugins/jira.py
- pyconjpbot/plugins/lgtm.py
- pyconjpbot/plugins/manual.py
- pyconjpbot/plugins/misc.py
- pyconjpbot/plugins/plusplus.py
- pyconjpbot/plugins/plusplus_model.py
- pyconjpbot/plugins/pycamp.py
- pyconjpbot/plugins/reaction.py
- pyconjpbot/plugins/suddendeath.py
- pyconjpbot/plugins/term.py
- pyconjpbot/plugins/term_model.py
- pyconjpbot/plugins/translator.py
- pyconjpbot/plugins/wikipedia.py
* https://pyconjp.atlassian.net/browse/ISSHA-2313
> ISSHA-2313 black, flake8, isort

- ChangeLog.txt
- pyconjpbot/google_plugins/gadmin.py
- pyconjpbot/google_plugins/google_api.py
- pyconjpbot/google_plugins/googledrive.py
- pyconjpbot/plugins/calc.py
- pyconjpbot/plugins/github.py
- pyconjpbot/plugins/jira.py
- pyconjpbot/plugins/lgtm.py
- pyconjpbot/plugins/manual.py
- pyconjpbot/plugins/misc.py
- pyconjpbot/plugins/plusplus.py
- pyconjpbot/plugins/pycamp.py
- pyconjpbot/plugins/term.py
- pyconjpbot/plugins/translator.py
- pyconjpbot/plugins/wikipedia.py
* https://pyconjp.atlassian.net/browse/ISSHA-2316
> ISSHA-2316 f-string

- ChangeLog.txt
- pyconjpbot/plugins/pycamp.py
* https://pyconjp.atlassian.net/browse/ISSHA-2209
> WIP: ISSHA-2209 fix pycamp createコマンド

- .github/workflows/linter.yml
- ChangeLog.txt
- README.md
- mypy.ini
- pyconjpbot/botmessage.py
- pyconjpbot/google_plugins/gadmin.py
- pyconjpbot/google_plugins/google_api.py
- pyconjpbot/google_plugins/google_search.py
- pyconjpbot/google_plugins/googledrive.py
- pyconjpbot/plugins/calc.py
- pyconjpbot/plugins/github.py
- pyconjpbot/plugins/greeting.py
- pyconjpbot/plugins/jira.py
- pyconjpbot/plugins/lgtm.py
- pyconjpbot/plugins/manual.py
- pyconjpbot/plugins/misc.py
- pyconjpbot/plugins/plusplus.py
- pyconjpbot/plugins/pycamp.py
- pyconjpbot/plugins/reaction.py
- pyconjpbot/plugins/suddendeath.py
- pyconjpbot/plugins/term.py
- pyconjpbot/plugins/translator.py
- pyconjpbot/plugins/wikipedia.py
- run.py
- tox.ini
* https://pyconjp.atlassian.net/browseISSHA-2354
> ISSHA-2354 mypy対応

- pyconjpbot/plugins/plusplus.py
- pyconjpbot/plugins/term.py
* Resolve #65 
* ありません
linter Actionがパスしたらマージします
> black 22.1.0で導入されたpower operatorのスペースの書式の変更を適用

- ChangeLog.txt
- pyconjpbot/google_plugins/gadmin.py
- pyconjpbot/plugins/misc.py
- pyconjpbot/plugins/plusplus.py
- pyconjpbot/plugins/reaction.py
- requirements-dev.txt
- requirements.txt
- tox.ini
* https://pyconjp.atlassian.net/browse/ISSHA-2699
* rtm startが使えなくなったので、暫定対応する
> ISSHA-2699 rtm connect
